# Generated by Django 5.0.6 on 2026-08-26 10:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Debt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "debt_type",
                    models.CharField(
                        choices=[
                            ("loan", "Loan (I Owe)"),
                            ("receivable", "Receivable (Owed to Me)"),
                        ],
                        default="loan",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Person or institution name", max_length=200
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "principal_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Original loan or debt amount",
                        max_digits=15,
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Annual interest rate as percentage (e.g. 12.5 for 12.5%)",
                        max_digits=5,
                    ),
                ),
                ("start_date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paid", "Paid Off"),
                            ("overdue", "Overdue"),
                            ("partial", "Partially Paid"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Debt",
                "verbose_name_plural": "Debts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DebtRepayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("date", models.DateField()),
                ("payment_method", models.CharField(default="cash", max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "debt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repayments",
                        to="debts.debt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Debt Repayment",
                "verbose_name_plural": "Debt Repayments",
                "ordering": ["-date"],
            },
        ),
    ]
