# Generated by Django 5.0.6 on 2026-08-23 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=200)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_photos/"
                    ),
                ),
                (
                    "preferred_currency",
                    models.CharField(
                        choices=[
                            ("TZS", "Tanzanian Shilling (TZS)"),
                            ("USD", "US Dollar (USD)"),
                            ("EUR", "Euro (EUR)"),
                            ("KES", "Kenyan Shilling (KES)"),
                        ],
                        default="TZS",
                        max_length=3,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        choices=[
                            ("Africa/Dar_es_Salaam", "Africa/Dar_es_Salaam (EAT)"),
                            ("Africa/Nairobi", "Africa/Nairobi (EAT)"),
                            ("UTC", "UTC"),
                        ],
                        default="Africa/Dar_es_Salaam",
                        max_length=50,
                    ),
                ),
                (
                    "monthly_income_target",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "monthly_savings_target",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
