# Generated by Django 5.0.6 on 2026-08-26 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_wallet", "0001_initial"),
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="account",
            field=models.ForeignKey(
                blank=True,
                help_text="Wallet/account this expense was paid from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="accounts_wallet.account",
            ),
        ),
        migrations.AddField(
            model_name="income",
            name="account",
            field=models.ForeignKey(
                blank=True,
                help_text="Wallet/account this income was received into",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incomes",
                to="accounts_wallet.account",
            ),
        ),
    ]
